# Generated by Django 4.2.7 on 2023-11-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('prompt', models.TextField(blank=True)),
                ('image_url', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
    ]
