# Generated by Django 4.2.7 on 2023-11-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
