# Generated by Django 4.2.7 on 2023-11-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_image_response_alter_image_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image',
        ),
    ]
