# Generated by Django 4.2.7 on 2023-11-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_image_elapsed_time_image_end_time_image_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='elapsed_time',
        ),
    ]
