# Generated by Django 4.2.7 on 2023-11-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0006_remove_image_elapsed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='elapsed_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
