# Generated by Django 4.2.7 on 2023-11-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_image_elapsed_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='prompt',
            new_name='user_input',
        ),
    ]
