# Generated by Django 4.2.7 on 2023-11-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0008_rename_prompt_prompt_user_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='elapsed_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
