# Generated by Django 4.2.7 on 2023-11-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0010_crossover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossover',
            old_name='json1',
            new_name='parent1',
        ),
        migrations.RenameField(
            model_name='crossover',
            old_name='json2',
            new_name='parent2',
        ),
    ]
