# Generated by Django 4.2.7 on 2023-11-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0011_rename_json1_crossover_parent1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossover',
            name='prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
