# Generated by Django 4.2.7 on 2023-11-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0012_crossover_prompt_prompt_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('attributes', models.TextField(blank=True)),
                ('prompt', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('elapsed_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
