# Generated by Django 4.2.7 on 2023-11-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0014_crossover_parent1_image_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossover',
            name='parent1_image_uuid',
        ),
        migrations.RemoveField(
            model_name='crossover',
            name='parent2_image_uuid',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uuid',
        ),
    ]
