# Generated by Django 4.2.7 on 2023-11-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0017_rename_prompt_imageprompt_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prompt',
            new_name='UserInput',
        ),
    ]
