# Generated by Django 4.2.7 on 2023-11-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0020_remove_crossover_parent1_image_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossover',
            name='parent1_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='crossover',
            name='parent2_image',
            field=models.URLField(blank=True),
        ),
    ]
