# Generated by Django 4.2.7 on 2023-11-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0021_crossover_parent1_image_crossover_parent2_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='existing_values',
            field=models.TextField(blank=True),
        ),
    ]
