# Generated by Django 4.2.7 on 2023-11-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0022_mutation_existing_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutation',
            old_name='existing_values',
            new_name='avoid_values',
        ),
    ]
