# Generated by Django 4.2.7 on 2023-11-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0023_rename_existing_values_mutation_avoid_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='mutation_type',
            field=models.CharField(default=' ', max_length=1),
        ),
    ]
