# Generated by Django 4.2.7 on 2023-11-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0025_image_revised_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutation',
            name='mutation_type',
        ),
    ]
