# Generated by Django 4.2.7 on 2023-11-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0026_remove_mutation_mutation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossover',
            name='session',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='session',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='session',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='session',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userinput',
            name='session',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
