# Generated by Django 4.2.7 on 2023-11-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0027_crossover_session_image_session_imageprompt_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossover',
            name='iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutation',
            name='iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinput',
            name='iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
