# Generated by Django 4.2.7 on 2023-11-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0029_userselectionfeedback_image_instance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userselectionfeedback',
            old_name='parent_1',
            new_name='parent1',
        ),
        migrations.RenameField(
            model_name='userselectionfeedback',
            old_name='parent_1_feedback',
            new_name='parent1_feedback',
        ),
        migrations.RenameField(
            model_name='userselectionfeedback',
            old_name='parent_1_json',
            new_name='parent1_json',
        ),
        migrations.RenameField(
            model_name='userselectionfeedback',
            old_name='parent_2',
            new_name='parent2',
        ),
        migrations.RenameField(
            model_name='userselectionfeedback',
            old_name='parent_2_feedback',
            new_name='parent2_feedback',
        ),
        migrations.RenameField(
            model_name='userselectionfeedback',
            old_name='parent_2_json',
            new_name='parent2_json',
        ),
    ]
