# Generated by Django 4.2.7 on 2023-11-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0030_rename_parent_1_userselectionfeedback_parent1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userselectionfeedback',
            old_name='parent1',
            new_name='parent1_id',
        ),
        migrations.RenameField(
            model_name='userselectionfeedback',
            old_name='parent2',
            new_name='parent2_id',
        ),
    ]
