# Generated by Django 4.2.7 on 2023-11-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0032_userinputinitial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselectionfeedback',
            name='unselected1_id',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='userselectionfeedback',
            name='unselected1_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userselectionfeedback',
            name='unselected2_id',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='userselectionfeedback',
            name='unselected2_json',
            field=models.TextField(blank=True),
        ),
    ]
