# Generated by Django 4.2.7 on 2023-11-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0033_userselectionfeedback_unselected1_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselectionfeedback',
            name='unselected1_id',
        ),
        migrations.RemoveField(
            model_name='userselectionfeedback',
            name='unselected1_json',
        ),
        migrations.RemoveField(
            model_name='userselectionfeedback',
            name='unselected2_id',
        ),
        migrations.RemoveField(
            model_name='userselectionfeedback',
            name='unselected2_json',
        ),
    ]
