# Generated by Django 4.2.7 on 2023-11-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0034_remove_userselectionfeedback_unselected1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossover',
            name='parent1_id',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='crossover',
            name='parent2_id',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
