# Generated by Django 4.2.7 on 2023-11-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0035_crossover_parent1_id_crossover_parent2_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('session', models.UUIDField(blank=True, default=None, null=True)),
                ('iteration', models.IntegerField(blank=True, null=True)),
                ('children_after_crossover', models.TextField(blank=True)),
                ('children_after_mutation', models.TextField(blank=True)),
            ],
        ),
    ]
