# Generated by Django 4.2.7 on 2023-12-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0037_userselectionfeedback_current_iteration_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='omit',
            field=models.BooleanField(default=False),
        ),
    ]
