# Generated by Django 4.2.7 on 2023-12-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0038_userinput_omit'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='attributes',
            field=models.TextField(blank=True),
        ),
    ]
