# Generated by Django 4.2.7 on 2023-12-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0039_image_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='omit',
        ),
        migrations.AddField(
            model_name='userinput',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
