# Generated by Django 4.2.7 on 2023-12-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0040_remove_userinput_omit_userinput_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossover',
            name='parent1_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crossover',
            name='parent2_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
