# Generated by Django 4.2.7 on 2023-12-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0041_alter_crossover_parent1_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('session', models.UUIDField(blank=True, default=None, null=True)),
                ('user_input', models.TextField(blank=True)),
                ('iteration', models.IntegerField(blank=True, null=True)),
                ('final_id', models.CharField(blank=True, max_length=8)),
                ('final_json', models.TextField(blank=True)),
                ('final_image', models.URLField(blank=True, null=True)),
                ('final_feedback', models.TextField(blank=True)),
                ('current_iteration_results', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('contact', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='userselectionfeedback',
            name='parent1_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userselectionfeedback',
            name='parent2_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
