# Generated by Django 4.2.7 on 2023-12-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0043_dalleerror'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DalleError',
        ),
    ]
