# Generated by Django 4.2.7 on 2023-12-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0044_delete_dalleerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
