# Generated by Django 4.2.7 on 2023-12-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0046_runcomplete'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('session', models.UUIDField(blank=True, default=None, null=True)),
                ('user_input', models.TextField(blank=True)),
                ('iteration', models.IntegerField(blank=True, null=True)),
                ('final_id', models.CharField(blank=True, max_length=8)),
                ('final_json', models.TextField(blank=True)),
                ('final_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
